export const ar = {
  common: {
    platformName: 'منصة مساعد اللغة العربية',
    assistantName: 'مساعد اللغة العربية',
    footerKuwait: 'منصة مساعد اللغة العربية • الكويت 🇰🇼',
    footerStages: 'منصة مساعد اللغة العربية • ابتدائي · متوسط · ثانوي',
    or: 'أو',
    cancel: 'إلغاء',
    logout: 'تسجيل الخروج',
    exit: 'خروج',
    gradePrefix: 'الصف',
    lessonCount: (n: number) => `${n} درس`,
    lessonCountSelected: (n: number) => `${n} درس محدد`,
    fileCount: (n: number) => `${n} ملف`,
    orderLabel: (n: number) => `الترتيب: ${n}`,
    stages: {
      primary: 'ابتدائي',
      middle: 'متوسط',
      high: 'ثانوي',
    } as Record<string, string>,
    grades: {
      primary: ['الأول', 'الثاني', 'الثالث', 'الرابع', 'الخامس'],
      middle: ['السادس', 'السابع', 'الثامن', 'التاسع'],
      high: ['العاشر', 'الحادي عشر', 'الثاني عشر'],
    },
    userType: {
      teacher: 'معلم',
      student: 'طالب',
      teacherBadge: '👨‍🏫 معلم',
      studentBadge: '👨‍🎓 طالب',
    },
    examType: {
      short: 'اختبار قصير',
      final: 'اختبار نهائي',
      shortBadge: '📝 قصير',
      finalBadge: '📊 نهائي',
    },
    errors: {
      generic: 'حدث خطأ',
      connection: 'خطأ في الاتصال.',
    },
    saving: '💾 جارٍ الحفظ...',
    savingShort: '⏳...',
  },

  login: {
    floatingWords: [
      'نحو', 'بلاغة', 'أدب', 'صرف', 'شعر', 'نثر',
      'قراءة', 'كتابة', 'تعبير', 'إملاء', 'خط', 'لغة',
    ],
    title: 'منصة مساعد اللغة العربية',
    subtitle: 'مدعوم بالذكاء الاصطناعي 🤖',
    emailPlaceholder: 'البريد الإلكتروني',
    passwordPlaceholder: 'كلمة المرور',
    forgotPassword: 'نسيت كلمة المرور؟ 🔑',
    loginButton: 'دخول ←',
    loggingIn: 'جارٍ الدخول...',
    registerButton: 'ليس لدي حساب — التسجيل الجديد ✨',
    errors: {
      missingCredentials: 'أدخل البريد الإلكتروني وكلمة المرور',
      loginFailed: 'خطأ في تسجيل الدخول',
      tryAgain: 'حدث خطأ. حاول مرة أخرى.',
    },
  },

  dashboard: {
    title: '🌙 مساعد اللغة العربية',
    greeting: (name: string) => `أهلاً ${name} 👋`,
    settings: {
      title: '⚙️ الإعدادات',
      themeColor: '🎨 لون المظهر',
      displayMode: '🌓 وضع العرض',
      modes: {
        dark: '🌙 داكن',
        light: '☀️ فاتح',
        system: '💻 حسب النظام',
      },
    },
    themeColors: [
      { name: 'ذهبي', value: '#f9d423', gradient: 'linear-gradient(135deg,#f9d423,#ff4e50)' },
      { name: 'أزرق', value: '#4facfe', gradient: 'linear-gradient(135deg,#4facfe,#00f2fe)' },
      { name: 'أخضر', value: '#43e97b', gradient: 'linear-gradient(135deg,#43e97b,#38f9d7)' },
      { name: 'بنفسجي', value: '#a78bfa', gradient: 'linear-gradient(135deg,#a78bfa,#ec4899)' },
      { name: 'برتقالي', value: '#f97316', gradient: 'linear-gradient(135deg,#f97316,#ef4444)' },
      { name: 'وردي', value: '#ec4899', gradient: 'linear-gradient(135deg,#ec4899,#8b5cf6)' },
    ],
    tools: [
      { id: 'explain', icon: '💡', label: 'شرح الدرس', desc: 'شرح مبسط مع أمثلة' },
      { id: 'worksheet', icon: '📋', label: 'ورقة عمل', desc: 'أنشطة تفاعلية' },
      { id: 'game', icon: '🎮', label: 'لعبة لغوية', desc: 'نشاط ممتع وتعليمي' },
      { id: 'plan', icon: '📖', label: 'تحضير الدرس', desc: 'خطة درس كاملة' },
      { id: 'pptx', icon: '📊', label: 'عرض PowerPoint', desc: 'شرائح جاهزة للعرض' },
      { id: 'exam', icon: '📝', label: 'اختبار', desc: 'أسئلة متنوعة' },
    ],
    steps: {
      subject: '① اختر المادة',
      unit: '② اختر الوحدة',
      lesson: '③ اختر الدرس',
      tool: '④ ماذا تريد؟',
      details: '⑤ تفاصيل إضافية (اختياري)',
    },
    noSubjects: 'لا توجد مواد متاحة — تواصل مع المدير',
    exams: {
      title: '📝 الاختبارات',
      short: '📝 قصير',
      final: '📊 نهائي',
      noneOfType: 'لا توجد اختبارات من هذا النوع',
    },
    placeholders: {
      explain: 'ركز على الأمثلة التطبيقية...',
      worksheet: '5 أنشطة متنوعة...',
      game: 'لعبة جماعية...',
      plan: 'درس 45 دقيقة...',
      default: '10 أسئلة الدرجة من 20...',
    },
    errors: {
      selectExam: 'اختر الاختبار أولاً',
      selectLesson: 'اختر الدرس أولاً',
      selectTool: 'اختر الأداة أولاً',
    },
    generating: '⏳ جارٍ الاستخراج...',
    generateExam: (name: string) => `✨ إنشاء ${name}`,
    generateTool: (label: string, lesson: string) => `✨ ${label} — ${lesson}`,
    copy: '📋 نسخ',
    copied: '✅ تم',
    material: {
      examName: (name: string) => `اسم الاختبار: ${name}`,
      examType: (type: string) => `نوع الاختبار: ${type}`,
      instructions: (desc: string) => `تعليمات: ${desc}`,
      lessonsContent: 'محتوى الدروس:',
      subject: (name: string) => `المادة: ${name}`,
      unit: (name: string) => `الوحدة: ${name}`,
      lesson: (name: string) => `الدرس: ${name}`,
      description: (desc: string) => `الوصف: ${desc}`,
      scientificContent: 'المادة العلمية:',
    },
    prompts: {
      prepareExam: (name: string) => `أعدّ ${name}`,
      toolForLesson: (label: string, lesson: string) => `${label} لدرس ${lesson}`,
    },
  },

  admin: {
    title: '⚙️ لوحة تحكم المدير',
    stats: {
      subjects: 'المواد',
      generations: 'التوليدات',
      users: 'المستخدمون',
      requests: 'طلبات',
    },
    tabs: {
      requests: '🔔 الطلبات',
      subjects: '📚 المواد',
      units: '📖 الوحدات',
      lessons: '✏️ الدروس',
      exams: '📝 الاختبارات',
    },
    requestsTab: {
      empty: 'لا توجد طلبات معلقة',
      stages: '📚 المراحل:',
      grade: '🎓 الصف:',
      approve: '✅ موافقة',
      reject: '❌ رفض',
    },
    subjects: {
      edit: '✏️ تعديل المادة',
      add: '➕ إضافة مادة جديدة',
      namePlaceholder: 'اسم المادة — مثال: اللغة العربية',
      descPlaceholder: 'وصف المادة (اختياري)',
      stage: 'المرحلة',
      grade: 'الصف',
      icon: 'الأيقونة',
      saveEdit: '💾 حفظ التعديل',
      addButton: '➕ إضافة المادة',
      list: (n: number) => `📚 المواد المضافة (${n})`,
      stageGrade: (stage: string, grade: string) => `${stage} — الصف ${grade}`,
    },
    units: {
      subject: '📚 المادة',
      edit: '✏️ تعديل الوحدة',
      add: (name: string) => `➕ إضافة وحدة في ${name}`,
      namePlaceholder: 'اسم الوحدة — مثال: نصوص وقراءة',
      descPlaceholder: 'وصف الوحدة (اختياري)',
      order: 'الترتيب',
      icon: 'الأيقونة',
      saveEdit: '💾 حفظ التعديل',
      addButton: '➕ إضافة الوحدة',
      list: (n: number) => `📖 الوحدات (${n})`,
    },
    lessons: {
      unit: '📖 الوحدة',
      edit: '✏️ تعديل الدرس',
      add: (name: string) => `➕ إضافة درس في ${name}`,
      namePlaceholder: 'اسم الدرس — مثال: المبتدأ والخبر',
      descPlaceholder: 'وصف الدرس (اختياري)',
      contentPlaceholder: 'المادة العلمية للدرس — القواعد والأمثلة والشواهد...',
      order: 'الترتيب',
      files: '📎 ملفات الدرس (اختياري)',
      upload: '📂 اسحب أو انقر للرفع',
      uploadHint: 'Word • PDF • صور',
      saveEdit: '💾 حفظ التعديل',
      addButton: '➕ إضافة الدرس',
      list: (n: number) => `✏️ الدروس (${n})`,
    },
    exams: {
      add: '➕ إضافة اختبار جديد',
      namePlaceholder: 'اسم الاختبار',
      type: 'نوع الاختبار',
      short: '📝 اختبار قصير',
      final: '📊 اختبار نهائي',
      selectLessons: (n: number) => `✏️ اختر الدروس (${n} محدد)`,
      descPlaceholder: 'تعليمات الاختبار أو ملاحظات إضافية (اختياري)',
      addButton: '➕ إضافة الاختبار',
      list: (n: number) => `📝 الاختبارات (${n})`,
    },
    messages: {
      enterSubjectName: '⚠️ أدخل اسم المادة',
      subjectUpdated: '✅ تم تعديل المادة',
      subjectAdded: '✅ تم إضافة المادة',
      selectSubjectFirst: '⚠️ اختر مادة أولاً',
      enterUnitName: '⚠️ أدخل اسم الوحدة',
      unitUpdated: '✅ تم تعديل الوحدة',
      unitAdded: '✅ تم إضافة الوحدة',
      selectUnitFirst: '⚠️ اختر وحدة أولاً',
      enterLessonName: '⚠️ أدخل اسم الدرس',
      lessonUpdated: '✅ تم تعديل الدرس',
      lessonAdded: '✅ تم إضافة الدرس',
      enterExamName: '⚠️ أدخل اسم الاختبار',
      selectSubjectForExam: '⚠️ اختر مادة للاختبار',
      selectLessonsForShortExam: '⚠️ اختر دروساً للاختبار القصير',
      examAdded: '✅ تم إضافة الاختبار',
    },
    confirms: {
      deleteSubject: 'حذف المادة وكل وحداتها ودروسها؟',
      deleteUnit: 'حذف الوحدة وكل دروسها؟',
      deleteLesson: 'حذف هذا الدرس؟',
      deleteExam: 'حذف الاختبار؟',
    },
  },
} as const

export const STAGES = [
  { id: 'primary', label: ar.common.stages.primary, grades: ar.common.grades.primary },
  { id: 'middle', label: ar.common.stages.middle, grades: ar.common.grades.middle },
  { id: 'high', label: ar.common.stages.high, grades: ar.common.grades.high },
]
